In [1]:
import numpy as np

## Vector Operations

In [2]:
u = np.array([1,2,3])
v = np.array([3,2,1])

In [3]:
u+v

array([4, 4, 4])

In [4]:
u*v

array([3, 4, 3])

In [5]:
2*u

array([2, 4, 6])

## Multiplications

### 1. Vector-Vector multiplication (Dot Product)

In [6]:
u.dot(v) # in numpy

10

In [7]:
u.shape[0]

3

In [8]:
def vector_vector_mul(u,v):
    assert u.shape[0] == v.shape[0]
    
    result = 0.0
    for i in range(u.shape[0]):
        result += u[i]*v[i]
        
    return result

In [9]:
vector_vector_mul(u,v)

10.0

### 2. Matrix-Vector Multiplication

In [10]:
u = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
u

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [11]:
v = np.array([1,0.5,2,1])
v

array([1. , 0.5, 2. , 1. ])

In [12]:
u.dot(v) # in numpy

array([20. ,  6. ,  8.5])

In [13]:
def mat_vector_mul(u,v):
    assert u.shape[1] == v.shape[0]
    
    result = np.zeros(u.shape[0])
    for i in range(u.shape[0]):
        result[i] = vector_vector_mul(u[i], v)
        
    return result

In [14]:
mat_vector_mul(u,v)

array([20. ,  6. ,  8.5])

### 3. Matrix-Matrix Multiplication

In [15]:
u = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
u

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [16]:
v = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])
v

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [17]:
u.dot(v) ## in numpy

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [18]:
def mat_mat_mul(u,v):
    assert u.shape[1] == v.shape[0]
    
    num_rows = u.shape[0]
    num_cols = v.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = v[:, i]
        Uvi = mat_vector_mul(u, vi)
        result[:, i] = Uvi
    
    return result 

In [19]:
mat_mat_mul(u,v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Matrix Inverse

In [21]:
u

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [22]:
u[:, :3] ## square matrix

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [23]:
np.linalg.inv(u[:, :3])

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [24]:
# np.linalg.inv(u) ## gives LinAlgError, as u is not sq mat.